# Generated by Django 5.1.7 on 2025-03-29 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_acesso', models.CharField(max_length=50, unique=True)),
                ('numero_celular', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'parametros',
            },
        ),
    ]
