# Generated by Django 5.1.7 on 2025-03-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametro',
            name='codigo_acesso',
            field=models.CharField(default='123456789', max_length=50, unique=True),
        ),
    ]
