# Generated by Django 5.1.7 on 2025-03-30 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='funcionario',
            field=models.BooleanField(default=False),
        ),
    ]
