# Generated by Django 5.1.7 on 2025-03-30 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_usuario_user_id_usuario_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='user',
            new_name='user_id',
        ),
    ]
