# Generated by Django 5.1.7 on 2025-03-29 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_usuario_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
