# Generated by Django 5.1.7 on 2025-03-29 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('duracao', models.DurationField(help_text='Duração estimada do serviço (ex: 00:30:00 para 30 minutos)')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'db_table': 'servicos',
            },
        ),
    ]
