# Generated by Django 5.1.7 on 2025-03-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_alter_servico_duracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
